# Generated by Django 3.0.5 on 2021-02-13 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20, verbose_name='Name')),
                ('color', models.TextField(choices=[('#FAEBD7', 'AntiqueWhite'), ('#7FFFD4', 'Aquamarine'), ('#DEB887', 'BurlyWood'), ('#FF7F50', 'Coral'), ('#FF8C00', 'DarkOrange'), ('#FFD700', 'Gold')], default='#FFD700', verbose_name='color')),
                ('adjustment', models.DecimalField(decimal_places=2, max_digits=6)),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VisitCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(max_length=150, verbose_name='user')),
                ('ip', models.TextField(max_length=50, null=True, verbose_name='ip')),
                ('timevisit', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exported', models.BooleanField(default=False, verbose_name='exported')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('paymode', models.PositiveIntegerField(choices=[(3, 'Cash')], default=3, verbose_name='paymode')),
                ('info', models.TextField(default='', max_length=15, verbose_name='info')),
                ('payee', models.TextField(default='', max_length=20, verbose_name='payee')),
                ('wording', models.TextField(default='', max_length=200, verbose_name='wording')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tags', models.TextField(default='', max_length=20, verbose_name='tags')),
                ('image', models.ImageField(blank=True, upload_to='purse/images', verbose_name='image')),
                ('currency', models.TextField(blank=True, default='€', max_length=8, verbose_name='currency')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purse.Account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
