# Generated by Django 3.0.5 on 2021-02-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='adjustment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.TextField(default='my purse', max_length=20, verbose_name='Name'),
        ),
    ]
