# Generated by Django 3.0.5 on 2021-02-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purse', '0002_auto_20210221_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cuantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
