# Generated by Django 3.0.5 on 2021-02-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purse', '0003_account_cuantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='color',
            field=models.CharField(choices=[('#FAEBD7', 'AntiqueWhite'), ('#7FFFD4', 'Aquamarine'), ('#DEB887', 'BurlyWood'), ('#FF7F50', 'Coral'), ('#FF8C00', 'DarkOrange'), ('#FFD700', 'Gold')], default='#FFD700', max_length=7, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(default='my purse', max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='currency',
            field=models.CharField(blank=True, default='€', max_length=8, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='info',
            field=models.CharField(default='', max_length=15, verbose_name='info'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payee',
            field=models.CharField(default='', max_length=20, verbose_name='payee'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='tags',
            field=models.CharField(default='', max_length=20, verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='wording',
            field=models.CharField(default='', max_length=200, verbose_name='wording'),
        ),
        migrations.AlterField(
            model_name='visitcounter',
            name='ip',
            field=models.CharField(max_length=50, null=True, verbose_name='ip'),
        ),
        migrations.AlterField(
            model_name='visitcounter',
            name='user',
            field=models.CharField(max_length=150, verbose_name='user'),
        ),
    ]
