# Generated by Django 3.0.5 on 2021-02-21 18:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('purse', '0004_auto_20210221_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='currency',
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.CharField(blank=True, default='€', max_length=8, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(default='my purse', max_length=40, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 2, 21, 18, 53, 2, 749144, tzinfo=utc), verbose_name='Date'),
        ),
    ]
