# Generated by Django 3.0.5 on 2021-02-21 19:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('purse', '0005_auto_20210221_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 2, 21, 19, 19, 43, 485765, tzinfo=utc), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='info',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='info'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payee',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='payee'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='tags'),
        ),
    ]
