# Generated by Django 3.0.5 on 2021-02-22 19:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('purse', '0007_auto_20210222_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='showexported',
            field=models.BooleanField(default=False, verbose_name='Show exported transactions'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 2, 22, 19, 38, 44, 464472, tzinfo=utc), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='showinactive',
            field=models.BooleanField(default=False, verbose_name='show inactive'),
        ),
    ]
