# Generated by Django 3.0.5 on 2021-02-22 19:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('purse', '0008_auto_20210222_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 2, 22, 19, 38, 48, 26952, tzinfo=utc), verbose_name='Date'),
        ),
    ]
