# Generated by Django 3.0.5 on 2021-02-27 09:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('purse', '0009_auto_20210222_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='showexported',
            field=models.BooleanField(default=False, verbose_name='Show exported expenses'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 2, 27, 9, 39, 46, 806038, tzinfo=utc), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='image',
            field=models.ImageField(blank=True, upload_to='purse/expenses', verbose_name='image'),
        ),
    ]
