# Generated by Django 3.0.11 on 2021-03-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purse', '0014_auto_20210305_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='adjustment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Adjustment'),
        ),
        migrations.AlterField(
            model_name='account',
            name='color',
            field=models.CharField(choices=[('backg01', 'AntiqueWhite'), ('backg02', 'Aquamarine'), ('backg03', 'BurlyWood'), ('backg04', 'Coral'), ('backg05', 'DarkOrange'), ('backg06', 'Gold')], default='#FFD700', max_length=7, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='account',
            name='cuantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Cuantity'),
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(blank=True, default='€', max_length=8, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(default='my purse', help_text='Purse/wallet name', max_length=40, verbose_name='Name'),
        ),
    ]
