# Generated by Django 3.0.11 on 2021-03-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purse', '0015_auto_20210309_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='showinactive',
            field=models.BooleanField(default=False, help_text='Activate to show inactive purses/wallets', verbose_name='Show inactive'),
        ),
        migrations.AlterField(
            model_name='visitcounter',
            name='timevisit',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date'),
        ),
    ]
