# Generated by Django 3.0.11 on 2021-03-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purse', '0016_auto_20210314_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(verbose_name='expense date'),
        ),
    ]
