# Generated by Django 3.0.11 on 2021-03-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purse', '0018_auto_20210314_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='expense',
            name='exported',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='expense',
            name='image',
            field=models.ImageField(blank=True, upload_to='purse/expenses'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='info',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payee',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='paymode',
            field=models.PositiveIntegerField(choices=[(3, 'Cash')], default=3),
        ),
        migrations.AlterField(
            model_name='expense',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='wording',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='visitcounter',
            name='app',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visitcounter',
            name='ip',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visitcounter',
            name='timevisit',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitcounter',
            name='user',
            field=models.CharField(max_length=150),
        ),
    ]
